Added_Image_Upload_feature
harsh-9in/Blogger pull request #100
Opened 2020-08-25 17:58 UTC by ManishShah120

# Description [about the feature]:
- Added a Front-End feature to upload an image by any user, while creating a Blog-Post.
- Tweaked the UI of the detail page to display the image for any blog-post, if the user has uploaded any image while creating that blog post, else the blog post would be displayed as usual.

Fixes: #92 
 
# GIF [FEATURE]
![ImageUploadFeature](https://user-images.githubusercontent.com/45564404/91209508-7b81c900-e729-11ea-8799-fe69b76cb4e5.gif)

2020-08-25 18:02 UTC, ManishShah120 commented
Hey @Kajol-Kumari, Can this be _merged_, else if there is anything I should change please let me know.

2020-08-28 09:06 UTC, Kajol-Kumari requested changes
Good Work!
Functionality is working fine. Please incorporate the suggested changes and it'll be good to go.

2020-08-28 09:06 UTC, Kajol-Kumari commented on mysite/blog/templates/blog/home.html
> +            <a href="{% url 'post-detail' slug=mostliked1.slug %}" class="readmorebutton">Read More</a>
Hey @ManishShah120 I can see here the changes from `slug` PR. Can you please remove all these unnecessary changes?

2020-08-28 16:03 UTC, ManishShah120 commented
Hey @Kajol-Kumari , I have made the required changes and solved the conflict. Please have a look.

2020-08-28 17:30 UTC, Kajol-Kumari approved these changes
LGTM :)

This can be merged now.

2020-08-28 17:48 UTC, ManishShah120 commented
@harsh-9in, I would love to see this **feature** added to this Project. Please let me know if there is any more changes I need to make for this _PR_ to get merged.

2020-08-29 06:43 UTC, merged