Resolved profile pic issue #167
harsh-9in/Blogger pull request #175
Opened 2020-09-23 12:33 UTC by kritikaparmar-programmer

Fixes: #167 

# Proposed Changes
 - Changes in profile.html
 
# Additional Info
  - Now profile pic is adding
  
# Screenshots
 
![profic ](https://user-images.githubusercontent.com/59971890/94013007-1d4b1300-fdc7-11ea-8033-8269448f0531.png)

2020-09-23 12:35 UTC, kritikaparmar-programmer commented
Hey @harsh-9in and @Kajol-Kumari I've done the changes Take a look now ..

2020-09-24 17:50 UTC, Kajol-Kumari requested changes
@kritikaparmar-programmer are you sure you have pushed the right change in this PR?  I am still facing the same issue when i tried pulling this code and runing it.

2020-09-24 17:53 UTC, kritikaparmar-programmer commented
Hey @Kajol-Kumari take a look now Sorry for inconvenience.

2020-09-25 17:08 UTC, Kajol-Kumari commented
@kritikaparmar-programmer I tested your PR and though the functionality is working fine, you have messed up the UI somehow.
![Screenshot from 2020-09-25 22-32-19](https://user-images.githubusercontent.com/44888949/94295856-870e1d00-ff7f-11ea-97c1-54c98c5eea73.png)

only the `save change` functionality is not working as we are able to get the dialogue box for image change and so you just need to fix that, rest we don't need any other form as we alredy have one for the image update.

2020-09-27 12:42 UTC, kritikaparmar-programmer commented
Hey @Kajol-Kumari take a look now. I removed the save changes button  as there was no option left.

2020-09-27 18:35 UTC, Kajol-Kumari requested changes

2020-09-27 18:35 UTC, Kajol-Kumari commented on mysite/users/templates/user/profile.html
> +
@kritikaparmar-programmer why do we need this code snippet from here to [here](https://github.com/harsh-9in/Blogger/pull/175/files#diff-8208737725c422c84328b370f39b3b24R39) when we already have the the same code from [here](https://github.com/harsh-9in/Blogger/pull/175/files#diff-8208737725c422c84328b370f39b3b24R95). Also if you remove the `save` button how will the image get update in the backend and in the user profile?

2020-09-29 07:54 UTC, kritikaparmar-programmer commented
Hey @Kajol-Kumari  and @harsh-9in Take a look now. I resolved the UI part and now the image is also updating.

2020-09-29 09:50 UTC, Kajol-Kumari approved these changes
Functionality is working fine now and it's good to go now :) 
Thanku @kritikaparmar-programmer for fixing this with patience.

2020-09-30 10:09 UTC, harsh-9in approved these changes

2020-09-30 10:10 UTC, merged