Bookmark feat
harsh-9in/Blogger pull request #176
Opened 2020-09-25 18:10 UTC by ManishShah120

# Description[about the feature]:
- Added the Bookmarking/Saving feature.
- Added an extra dropdown menu under the profile section.

Fixes: #171 

# Additional Info:
  - Converted the `post-detail` view from a class-based view to a function-based view, so as a result more features and functions can be added to the post-detailed view/page in the future.
  - Added an extra separate page for displaying all the saved/bookmarked blogs for any specific user.
  - Also added feature to remove the previously saved/bookmarked blog-posts.
  - Added a condition for allowing only logged in user to be able to save or bookmarks.
  
# Screenshots/Gif:
![BookMark_Feature](https://user-images.githubusercontent.com/45564404/94300248-58e00b80-ff86-11ea-86c4-7fa30fb8bf38.gif)

2020-09-25 18:12 UTC, ManishShah120 commented
@harsh-9in & @Kajol-Kumari , Please have a look.

2020-09-27 06:24 UTC, Kajol-Kumari requested changes
@ManishShah120 Please incorporate the suggested changes, Rest LGTM :)

2020-09-27 06:24 UTC, Kajol-Kumari commented on mysite/blog/templates/blog/base.html
> +                          <a class="dropdown-item" href="{% url 'users:favourite_list' %}">Saved Blogs</a>
Please replace `saved Blogs` with `My Favourite blogs`

2020-09-27 06:24 UTC, Kajol-Kumari commented on mysite/users/templates/user/favourites.html
> +    <h2>Favourites</h2>
Let's keep the heading here as `My Favourite Blogs`

2020-09-27 06:24 UTC, Kajol-Kumari commented on mysite/users/urls.py
> +]
please leave one blank line at the end of the file.

2020-09-27 06:24 UTC, Kajol-Kumari commented on mysite/users/templates/user/favourites.html
> +{% endblock %}
please left one extra line here.

2020-09-27 10:11 UTC, ManishShah120 commented
@Kajol-Kumari , I have resolved the requested changes. Can it be merged now?

2020-09-27 18:27 UTC, Kajol-Kumari approved these changes
LGTM :+1: 
@harsh-9in this can be merged now!

2020-09-29 05:02 UTC, harsh-9in reviewed
@ManishShah120 plz remove conflicts.

2020-09-29 07:28 UTC, ManishShah120 commented
@harsh-9in, removed the conflict.

2020-09-29 08:51 UTC, harsh-9in approved these changes
@ManishShah120 plz remove conflicts.

2020-09-29 08:51 UTC, merged